<Project Sdk="Godot.NET.Sdk/4.3.0">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net7.0</TargetFramework>
        <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'ios' ">net8.0</TargetFramework>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <StartAction>Program</StartAction>
        <StartProgram>/home/gaugamela/AppImages/Godot/Godot_v4.3-stable_mono_linux_x86_64/Godot_v4.3-stable_mono_linux.x86_64</StartProgram>
        <StartWorkingDirectory>./</StartWorkingDirectory>
    </PropertyGroup>
    <ItemGroup>
        <Content Include="Common\Assets\Triangle.svg" />
        <Content Include="Common\Assets\Triangle.svg.import" />
        <Content Include="Common\Shaders\WebMercatorToWGS84Shader.gdshader"/>
        <Content Include="Core\Languages\Generators\generate.sh" />
        <Content Include="Core\Languages\ProtocolXMLConversionDefinitions\common_to_hellenic.xml" />
        <Content Include="Core\Languages\ProtocolXMLDefinitions\common.xml" />
        <Content Include="Core\Languages\ProtocolXMLDefinitions\hellenic.xml" />
        <Content Include="Core\Languages\ProtocolXMLDefinitions\minimal.xml" />
        <Content Include="Core\Languages\ProtocolXMLDefinitions\standard.xml" />
        <Content Include="Core\Machine\Assets\Images\BoatIcon.png" />
        <Content Include="Core\Machine\Assets\Images\BoatIcon.png.import" />
        <Content Include="Core\Machine\Assets\Images\JetIcon.png" />
        <Content Include="Core\Machine\Assets\Images\JetIcon.png.import" />
        <Content Include="Core\Machine\Assets\Images\QuadcopterIcon.png" />
        <Content Include="Core\Machine\Assets\Images\QuadcopterIcon.png.import" />
        <Content Include="Core\SolarSystem\Assets\ESO_-_Milky_Way.jpg" />
        <Content Include="Core\SolarSystem\Assets\ESO_-_Milky_Way.jpg.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_0_10.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_0_32.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_0_32.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_0_42.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_0_8.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_10_15.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_10_20.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_10_28.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_10_52.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_10_58.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_10_59.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_11_22.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_11_26.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_11_29.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_11_34.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_12_12.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_12_16.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_12_19.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_12_40.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_12_54.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_13_3.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_13_38.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_13_49.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_13_6.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_14_17.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_14_2.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_14_20.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_14_22.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_14_60.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_14_63.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_15_10.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_15_18.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_15_39.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_15_41.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_15_58.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_16_12.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_16_17.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_16_21.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_16_21.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_16_31.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_16_41.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_16_58.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_17_13.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_17_16.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_17_18.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_17_49.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_17_50.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_17_60.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_18_22.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_18_30.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_18_47.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_19_37.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_19_37.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_19_39.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_19_55.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_19_56.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_1_28.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_1_33.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_1_44.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_1_46.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_1_5.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_1_51.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_1_6.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_1_61.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_20_54.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_20_6.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_21_12.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_21_19.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_21_19.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_21_23.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_21_24.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_21_42.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_21_46.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_21_48.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_21_7.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_22_16.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_22_19.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_22_27.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_22_37.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_22_39.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_22_45.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_22_50.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_22_52.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_22_63.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_22_9.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_23_0.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_23_10.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_23_14.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_23_4.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_24_23.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_24_38.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_25_14.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_25_25.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_25_27.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_26_10.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_26_15.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_26_17.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_26_31.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_26_46.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_26_48.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_26_56.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_26_61.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_26_7.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_27_15.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_27_38.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_27_41.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_27_53.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_27_6.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_28_15.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_28_54.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_28_54.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_29_11.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_29_23.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_29_46.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_29_47.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_29_54.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_29_55.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_29_63.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_2_1.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_2_2.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_2_50.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_30_22.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_30_33.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_30_40.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_30_46.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_30_51.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_30_57.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_30_61.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_30_63.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_31_15.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_31_28.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_31_28.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_31_5.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_31_5.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_31_56.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_31_63.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_32_40.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_32_48.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_32_8.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_33_0.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_33_40.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_33_54.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_33_58.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_33_60.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_33_7.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_34_22.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_34_42.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_34_48.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_34_7.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_35_15.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_35_16.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_35_18.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_35_39.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_35_40.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_35_42.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_35_60.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_36_11.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_36_4.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_36_62.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_37_0.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_37_10.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_37_45.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_37_47.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_37_6.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_38_16.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_38_19.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_38_2.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_38_28.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_38_32.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_38_58.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_38_61.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_39_10.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_39_21.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_39_29.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_39_39.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_39_40.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_39_45.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_39_53.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_3_18.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_3_47.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_3_52.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_3_53.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_3_61.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_40_1.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_40_13.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_40_25.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_40_30.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_40_31.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_40_31.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_40_39.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_40_49.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_40_50.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_40_52.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_40_7.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_41_27.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_41_31.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_41_39.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_41_44.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_41_50.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_41_51.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_41_56.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_42_25.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_42_33.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_42_44.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_42_58.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_43_18.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_43_25.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_43_26.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_43_29.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_43_40.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_43_48.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_43_5.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_43_7.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_44_2.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_44_27.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_44_40.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_44_55.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_44_7.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_45_19.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_45_21.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_45_26.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_45_44.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_46_26.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_46_27.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_46_28.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_46_32.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_46_32.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_46_38.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_46_62.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_47_3.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_47_3.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_47_5.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_47_63.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_47_7.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_48_11.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_48_27.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_48_28.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_48_40.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_48_45.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_49_27.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_49_29.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_49_31.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_49_45.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_4_46.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_4_46.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_4_55.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_50_15.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_50_20.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_50_24.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_50_53.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_51_16.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_51_55.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_51_61.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_51_7.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_52_20.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_52_29.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_52_34.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_52_7.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_53_3.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_53_31.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_53_54.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_53_57.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_54_33.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_54_4.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_55_10.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_55_18.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_55_29.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_55_5.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_55_55.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_55_6.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_56_32.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_57_19.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_57_36.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_57_57.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_58_14.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_58_24.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_58_27.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_58_31.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_58_61.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_58_8.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_59_26.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_5_1.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_5_31.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_5_32.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_5_47.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_60_11.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_60_16.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_60_18.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_60_27.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_60_35.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_60_4.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_61_39.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_61_50.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_61_53.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_61_61.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_62_10.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_62_12.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_62_14.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_62_26.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_62_30.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_62_51.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_63_14.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_63_21.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_63_26.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_63_29.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_63_35.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_63_44.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_63_45.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_63_46.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_63_63.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_6_15.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_6_24.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_6_27.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_6_31.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_6_33.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_6_56.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_7_37.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_7_58.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_8_11.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_8_25.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_8_42.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_8_58.png" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_9_0.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_9_17.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_9_25.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_9_60.png.import" />
        <Content Include="Core\SolarSystem\Planets\Earth\Assets\MapTiles\Bing\SATELLITE\png\en\6\tile_9_7.png.import" />
        <Content Include="Core\SolarSystem\SolarSystem.tscn" />
        <Content Include="Core\UI\Fonts\Equinox\Equinox Bold.otf" />
        <Content Include="Core\UI\Fonts\Equinox\Equinox Bold.otf.import" />
        <Content Include="Core\UI\Fonts\Equinox\Equinox Regular.otf" />
        <Content Include="Core\UI\Fonts\Equinox\Equinox Regular.otf.import" />
        <Content Include="Core\UI\Fonts\Jura\Jura-Bold.ttf" />
        <Content Include="Core\UI\Fonts\Jura\Jura-Bold.ttf.import" />
        <Content Include="Core\UI\Fonts\Jura\Jura-Light.ttf" />
        <Content Include="Core\UI\Fonts\Jura\Jura-Light.ttf.import" />
        <Content Include="Core\UI\Fonts\Jura\Jura-Medium.ttf" />
        <Content Include="Core\UI\Fonts\Jura\Jura-Medium.ttf.import" />
        <Content Include="Core\UI\Fonts\Jura\Jura-Regular.ttf" />
        <Content Include="Core\UI\Fonts\Jura\Jura-Regular.ttf.import" />
        <Content Include="Core\UI\Fonts\Jura\Jura-SemiBold.ttf" />
        <Content Include="Core\UI\Fonts\Jura\Jura-SemiBold.ttf.import" />
        <Content Include="Core\UI\Themes\DefaultHermesTheme.tres" />
        <Content Include="Core\UI\UIComponents\CompassDisplay\CompassDisplay.tscn" />
        <Content Include="docs\Hermes.png" />
        <Content Include="docs\Hermes.png.import" />
        <Content Include="docs\README_Images\MavgenGUIOutputExample.png" />
        <Content Include="docs\README_Images\MavgenGUIExample.png" />
        <Content Include="docs\Rules\csharp-style-guide.md" />
        <Content Include="docs\Rules\shader-style-guide.md" />
    </ItemGroup>
    <ItemGroup>
        <Compile Remove="**/submodules/**/*.cs"/>
    </ItemGroup>
    <ItemGroup>
        <Folder Include="Core\UI\Assets\" />
        <Folder Include="Core\UI\Themes\" />
        <Folder Include="Core\UI\UIComponents\BottomPanel\" />
        <Folder Include="Core\UI\UIComponents\CompassDisplay\" />
        <Folder Include="Core\UI\UIComponents\MachineCardPanel\" />
        <Folder Include="Core\UI\UIComponents\MachineCard\" />
        <Folder Include="Core\UI\UIComponents\MachineControl\ConfirmationSlider\" />
        <Folder Include="Core\UI\UIComponents\MachineControl\LandControlComponent\" />
        <Folder Include="Core\UI\UIComponents\MachineControl\TakeoffControlComponent\" />
        <Folder Include="Core\UI\UIScreens\HermesUI\" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3"/>
    </ItemGroup>
</Project>
