extends Node
class_name VehicleTypes

enum VehicleType {
	GENERIC_FIXED_WING,
	
	# MULTICOPTER TYPES
	GENERIC_MULTICOPTER,
	GENERIC_QUADCOPTER,
	GENERIC_HEXACOPTER,
	GENERIC_OCTOCOPTER,
	
	GENERIC_ROVER,
	GENERIC_SUBMARINE,
	GENERIC_SURFACE_VESSEL,
	F35_C_LIGHTNING,
	SR_71_BLACKBIRD,
	SATURN_V,
	UNKNOWN
}
